# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Weighted, more \code{nbins}-restrictive version of \code{base::tabulate}
#'
#' @param bin integer-compatible vector; entries must be non-NA and between 1
#' and \code{nbins}; these indices denote entries in the result vector to which
#' the corresponding weights in \code{w} should be added
#' @param nbins single non-NA, non-negative integer; length of the vector to
#' return
#' @param w numeric-compatible vector of the same length as \code{bin}; weights
#' corresponding to the indices in \code{bin}
#' @return numeric vector of length \code{nbins}; the \code{i}th entry is like
#' \code{sum(w[bin==i])}, but with a naive summation algorithm
#'
#' @export
weighted_tabulate <- function(bin, nbins, w) {
    .Call('_epiforecast_WeightedTabulateRcpp', PACKAGE = 'epiforecast', bin, nbins, w)
}

